#############################################################
##### Configuration File for JWST Coronagraphy Pipeline #####
#############################################################

##### Directories #####
idir: '/Users/acarter/Documents/DIRECT_IMAGING/JWST/HIFI_SIMS/NIRCam/20220209/jwst_s1s2_data/' # Input Directory
odir: '/Users/acarter/Documents/DIRECT_IMAGING/JWST/HIFI_SIMS/PIPELINE_REDUCE/TESTING/' # Output Directory
transmissiondir: '/Users/acarter/Documents/DIRECT_IMAGING/JWST/HIFI_SIMS/ANCILLARY/transmissions/'
psfmaskdir: '../psfmasks/'
offsetpsfdir: '../offsetpsfs/' # directory for the offset PSFs (will be generated automatically using WebbPSF)

##### General Settings #####
verbose: True
use_psfmask: True # if true use PSF masks from CRDS, if false use transmission functions
fiducial_point_override: True # if true uses narrow end of the bar masks, if false use filter dependent position

##### PSF Subtraction Settings #####
mode: ['RDI']       # list of modes for pyKLIP, will loop through all
annuli: [1]         # list of number of annuli for pyKLIP, will loop through all
subsections: [1]    # list of number of annuli for pyKLIP, will loop through all
numbasis: [1, 2, 5, 10, 20, 50, 100] # list of number of basis vectors for pyKLIP, will loop through all

##### Contrast Curve Settings #####
KL: -1 # index of the KL component for which the calibrated contrast curve and the companion properties shall be computed

ra_off: [418.] # mas; RA offset of the known companions in the same order as in the NIRCCoS config file
de_off: [-698.] # mas; DEC offset of the known companions in the same order as in the NIRCCoS config file

seps_inject_rnd: [5.0, 7.5, 10.0, 12.5, 15.0, 17.5, 20.0, 25., 30.0, 35.0, 40.0] # pix; list of separations at which fake planets shall be injected to compute the calibrated contrast curve for the round masks
pas_inject_rnd: [0., 45., 90., 135., 180., 225., 270., 315.] # deg; list of position angles at which fake planets shall be injected to compute the calibrated contrast curve for the round masks

pa_ranges_bar: [(105.-15., 105.+15.), (285.-15., 285.+15.)] # deg; list of tuples defining the pizza slices that shall be considered when computing the contrast curves for the bar masks
seps_inject_bar: [2.0, 4.0, 6.0, 8.0, 10.0, 12.5, 15.0, 17.5, 20.0, 25.0, 30.0] # pix; list of separations at which fake planets shall be injected to compute the calibrated contrast curve for the bar masks
pas_inject_bar: [45., 135., 225., 315.] # deg; list of position angles at which fake planets shall be injected to compute the calibrated contrast curve for the bar masks

